### ISSUE TITLE
10:49:03 PM: [error] 'App' is not exported by ../../node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by plugins/oruga.js

### ISSUE THREAD

**Issue by wesdevpro** [ntohq/ntohq-website#1]
# The Problem
Netlify is not happy with the plugin for Oruga. 

> ### The Site's Status
>> [![Netlify Status](https://api.netlify.com/api/v1/badges/f55964cc-4e48-4dcd-a366-d151d33f77cf/deploy-status)](https://app.netlify.com/sites/ntohqdevs/deploys)

## Logs
```
10:48:35 PM: Build ready to start
10:48:37 PM: build-image version: 8b79b5e0c585f1b3f892b8032389b4b4b188d887 (focal)
10:48:37 PM: build-image tag: v4.14.0
10:48:37 PM: buildbot version: 1e88a9b854b49555d21dc539e2b8bf5fb78a8f57
10:48:37 PM: Fetching cached dependencies
10:48:38 PM: Starting to download cache of 235.9KB
10:48:38 PM: Finished downloading cache in 38.529173ms
10:48:38 PM: Starting to extract cache
10:48:38 PM: Finished extracting cache in 4.622893ms
10:48:38 PM: Finished fetching cache in 88.428929ms
10:48:38 PM: Starting to prepare the repo for build
10:48:38 PM: Preparing Git Reference refs/heads/development
10:48:38 PM: Parsing package.json dependencies
10:48:39 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'packages/dist' versus '/packages/dist' in the Netlify UI
10:48:39 PM: Starting build script
10:48:39 PM: Installing dependencies
10:48:39 PM: Python version set to 2.7
10:48:39 PM: v16.18.0 is already installed.
10:48:40 PM: Now using node v16.18.0 (npm v8.19.2)
10:48:40 PM: Enabling node corepack
10:48:40 PM: Started restoring cached build plugins
10:48:40 PM: Finished restoring cached build plugins
10:48:40 PM: Attempting ruby version 2.7.2, read from environment
10:48:40 PM: Using ruby version 2.7.2
10:48:41 PM: Using PHP version 8.0
10:48:41 PM: Started restoring cached yarn cache
10:48:41 PM: Finished restoring cached yarn cache
10:48:41 PM: yarn workspaces detected
10:48:41 PM: Installing NPM modules using Yarn version 1.22.19
10:48:41 PM: yarn install v1.22.19
10:48:41 PM: [1/4] Resolving packages...
10:48:42 PM: [2/4] Fetching packages...
10:48:51 PM: warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
10:48:51 PM: [3/4] Linking dependencies...
10:48:51 PM: warning "workspace-aggregator-18bd81cd-bfb3-4aef-a2ee-007e6ceb753a > client > @oruga-ui/oruga-next@0.5.6" has unmet peer dependency "vue@^3.0.0".
10:48:51 PM: warning "workspace-aggregator-18bd81cd-bfb3-4aef-a2ee-007e6ceb753a > client > sass-loader@13.1.0" has unmet peer dependency "webpack@^5.0.0".
10:48:52 PM: [4/4] Building fresh packages...
10:48:54 PM: success Saved lockfile.
10:48:54 PM: Done in 12.23s.
10:48:54 PM: NPM modules installed using Yarn
10:48:54 PM: Started restoring cached go cache
10:48:54 PM: Finished restoring cached go cache
10:48:54 PM: Installing Go version 1.17 (requested 1.17)
10:48:58 PM: unset GOOS;
10:48:58 PM: unset GOARCH;
10:48:58 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
10:48:58 PM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
10:48:58 PM: go version >&2;
10:48:58 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
10:48:58 PM: go version go1.17 linux/amd64
10:48:58 PM: Installing missing commands
10:48:58 PM: Verify run directory
10:49:00 PM: ​
10:49:00 PM: ────────────────────────────────────────────────────────────────
10:49:00 PM:   Netlify Build                                                 
10:49:00 PM: ────────────────────────────────────────────────────────────────
10:49:00 PM: ​
10:49:00 PM: ❯ Version
10:49:00 PM:   @netlify/build 28.1.1
10:49:00 PM: ​
10:49:00 PM: ❯ Flags
10:49:00 PM:   baseRelDir: true
10:49:00 PM:   buildId: 63575c93a2b99376f90ea222
10:49:00 PM:   deployId: 63575c93a2b99376f90ea224
10:49:00 PM: ​
10:49:00 PM: ❯ Current directory
10:49:00 PM:   /opt/build/repo
10:49:00 PM: ​
10:49:00 PM: ❯ Config file
10:49:00 PM:   No config file was defined: using default values.
10:49:00 PM: ​
10:49:00 PM: ❯ Context
10:49:00 PM:   production
10:49:00 PM: ​
10:49:00 PM: ────────────────────────────────────────────────────────────────
10:49:00 PM:   1. Build command from Netlify app                             
10:49:00 PM: ────────────────────────────────────────────────────────────────
10:49:00 PM: ​
10:49:00 PM: $ yarn workspace client build
10:49:00 PM: yarn workspace v1.22.19
10:49:00 PM: yarn run v1.22.19
10:49:00 PM: $ nuxt build
10:49:00 PM: [log] Nuxi 3.0.0-rc.12
10:49:00 PM: [log] Nuxt 3.0.0-rc.12 with Nitro 0.6.0
10:49:02 PM: [warn] [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
10:49:02 PM: 459|    appearance: none;
10:49:02 PM: 460|    -webkit-print-color-adjust: exact;
10:49:02 PM: 461|    color-adjust: exact;
10:49:02 PM:    |     ^
10:49:02 PM: 462|    flex-shrink: 0;
10:49:02 PM: 463|    cursor: pointer;
10:49:02 PM: [warn] [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
10:49:02 PM: 1262|    appearance: none;
10:49:02 PM: 1263|    -webkit-print-color-adjust: exact;
10:49:02 PM: 1264|    color-adjust: exact;
10:49:02 PM:    |     ^
10:49:02 PM: 1265|    border-radius: 50%;
10:49:02 PM: 1266|    cursor: pointer;
10:49:03 PM: [error] 'App' is not exported by ../../node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by plugins/oruga.js
10:49:03 PM: file: /opt/build/repo/packages/client/plugins/oruga.js:1:20
10:49:03 PM: 1: import { createApp, App } from 'vue'
10:49:03 PM:                        ^
10:49:03 PM: 2: import Oruga from '@oruga-ui/oruga-next'
10:49:03 PM: 3: import '@oruga-ui/oruga-next/dist/oruga.css'
10:49:03 PM: [error] 'App' is not exported by ../../node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by plugins/oruga.js
10:49:03 PM:   at error (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
10:49:03 PM:   at Module.error (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
10:49:03 PM:   at Module.traceVariable (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
10:49:03 PM:   at ModuleScope.findVariable (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
10:49:03 PM:   at Identifier.bind (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
10:49:03 PM:   at CallExpression.bind (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
10:49:03 PM:   at CallExpression.bind (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
10:49:03 PM:   at MemberExpression.bind (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
10:49:03 PM:   at MemberExpression.bind (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:8616:19)
10:49:03 PM:   at CallExpression.bind (/opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
10:49:03 PM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
10:49:03 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:49:03 PM: error Command failed.
10:49:03 PM: Exit code: 1
10:49:03 PM: Command: /opt/buildhome/.nvm/versions/node/v16.18.0/bin/node
10:49:03 PM: Arguments: /opt/buildhome/.cache/node/corepack/yarn/1.22.19/lib/cli.js build
10:49:03 PM: Directory: /opt/build/repo/packages/client
10:49:03 PM: Output:
10:49:03 PM: info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
10:49:03 PM: ​
10:49:03 PM: ────────────────────────────────────────────────────────────────
10:49:03 PM:   "build.command" failed                                        
10:49:03 PM: ────────────────────────────────────────────────────────────────
10:49:03 PM: ​
10:49:03 PM:   Error message
10:49:03 PM:   Command failed with exit code 1: yarn workspace client build (https://ntl.fyi/exit-code-1)
10:49:03 PM: ​
10:49:03 PM:   Error location
10:49:03 PM:   In Build command from Netlify app:
10:49:03 PM:   yarn workspace client build
10:49:03 PM: ​
10:49:03 PM:   Resolved config
10:49:03 PM:   build:
10:49:03 PM:     command: yarn workspace client build
10:49:03 PM:     commandOrigin: ui
10:49:03 PM:     publish: /opt/build/repo/packages/dist
10:49:03 PM:     publishOrigin: ui
10:49:03 PM: Caching artifacts
10:49:03 PM: Started saving workspace packages/client node modules
10:49:03 PM: Finished saving workspace packages/client node modules
10:49:03 PM: Started saving workspace packages/server node modules
10:49:03 PM: Finished saving workspace packages/server node modules
10:49:03 PM: Started saving workspace root node modules
10:49:03 PM: Finished saving workspace root node modules
10:49:03 PM: Started saving build plugins
10:49:03 PM: Finished saving build plugins
10:49:03 PM: Started saving yarn cache
10:49:05 PM: Finished saving yarn cache
10:49:05 PM: Started saving pip cache
10:49:05 PM: Finished saving pip cache
10:49:05 PM: Started saving emacs cask dependencies
10:49:05 PM: Finished saving emacs cask dependencies
10:49:05 PM: Started saving maven dependencies
10:49:05 PM: Finished saving maven dependencies
10:49:05 PM: Started saving boot dependencies
10:49:05 PM: Finished saving boot dependencies
10:49:05 PM: Started saving rust rustup cache
10:49:05 PM: Finished saving rust rustup cache
10:49:05 PM: Started saving go dependencies
10:49:05 PM: Finished saving go dependencies
10:49:05 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:49:05 PM: Creating deploy upload records
10:49:06 PM: Failing build: Failed to build site
10:49:06 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
10:49:06 PM: Finished processing build request in 28.494491429s
[Docs](https://docs.netlify.com/)
[Pricing](https://www.netlify.com/pricing/)
[Support](https://www.netlify.com/support)
[News](https://www.netlify.com/news/)
[Terms](https://www.netlify.com/tos/)
© 2022 Netlify
```

**Comment by wesdevpro** [comment]
The following error: ```[error] 'default' is not exported by plugins/oruga.js, imported by virtual:nuxt:/opt/build/repo/packages/client/.nuxt/plugins/client.mjs``` came from development@eff5658

**Comment by wesdevpro** [comment]
Both errors have been fixed by changing the plugin/oruga.js code to match the official Oruga website.  The Netlify build command was changed from `yarn workspace client build` to `yarn workspace client generate` and the dist folder location was changed to `/packages/client/dist`
